// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGVP0bICTGhS6ZTRd6DrkfjYZSr43dlJo',
    appId: '1:1082491804467:web:ce9befa09a735269c67c46',
    messagingSenderId: '1082491804467',
    projectId: 'csen268-s25-g3',
    authDomain: 'csen268-s25-g3.firebaseapp.com',
    storageBucket: 'csen268-s25-g3.firebasestorage.app',
    measurementId: 'G-29R5BGZBYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7pHZ9WK1xYVJwn-a9inlYdbB7he97KkY',
    appId: '1:1082491804467:android:5f01cf281338f6ebc67c46',
    messagingSenderId: '1082491804467',
    projectId: 'csen268-s25-g3',
    storageBucket: 'csen268-s25-g3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2iKcsHc7MKuWM2QXBYLJLIva1UivdZs0',
    appId: '1:1082491804467:ios:0c841a2e9a9ebc4ec67c46',
    messagingSenderId: '1082491804467',
    projectId: 'csen268-s25-g3',
    storageBucket: 'csen268-s25-g3.firebasestorage.app',
    iosBundleId: 'com.example.books',
  );
}
